# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        user:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            anonymous: ~
            provider: user
            form_login:
                login_path: login
                check_path: login
                failure_path: login
            logout:
                path:   /logout
                target: /
        secured_area:
            pattern: ^/
            form_login: ~
