language: php
php:
  - '5.6'
  - '7.0'

before_script: 
  - cd Symfony/
  - curl -sS https://getcomposer.org/installer | php
  - sudo chown -R `whoami`:`whoami` var
  - ./composer.phar install
  - sudo chown -R `whoami`:`whoami` var


script:
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - vendor/bin/phpunit -c . --coverage-clover clover.xml
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpcpd src/

after_success:
  - travis_retry php vendor/bin/coveralls


notifications:
  irc: "chat.freenode.net#codebender.cc"
  email:
    recipients:
      - girder@codebender.cc
  slack:
    secure: JKGrALsULcD+Wr2tWsE4SrFJ3JodCmtRF5ITVCnhAqChgu8nMAy6wm3n0GWLDccIyJqFtZT49KwYgWQ9gK67bilQoYdhdaVgkjDng6/NTp8gD8E2oM88OZKMcmNraLm9bVGaL3YgWLThDrraZRnE1FnWOjIOanISJAoH4TrT6vs=
